name: Cppcheck

 on: 
   push:
     branches:
       - '*'

 jobs:
   build:
     name: cppcheck-job
     runs-on: runner
     steps:
       - name: checkout
         uses: actions/checkout@v3.5.3
         
     - name: Publish Test Results
       uses: EnricoMi/publish-unit-test-result-action@v2.8.0
       
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action/composite@v2
          if: always()
          with:
           files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json
