
SHELL := /bin/bash
CURRENT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

all: clean setup test

clean:
	@echo "Clean"
	

setup:
	@echo "Setup"
	

test:
	@echo "Run Tests"
	

test-phantomjs:
	@echo "Run Tests"
	