name: Cppcheck

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    name: cppcheck-job
    runs-on: runner
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        
      - name: cppcheck-action
        uses: deep5050/cppcheck-action@v3.0
        
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
        
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' # your branch name goes here
