name: cppcheck
version: git
version-script: |
    echo $(cd parts/cppcheck/src; git describe --tags)
summary: A tool for static C/C++ code analysis
description: Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers and many other analysis tools it does not detect syntax errors in the code. Cppcheck primarily detects the types of bugs that the compilers normally do not detect.
confinement: strict
grade: stable

parts:
    cppcheck:
        plugin: make
        source-type: git
        source: https://github.com/danmar/cppcheck.git
        make-parameters:
            - FILESDIR=/snap/cppcheck/current/config

        build-packages:
            - gcc
            - make

        organize:
                snap/cppcheck/current/config: config

        filesets:
            all:
                - usr/bin/*
                - config/*
        stage: [$all]
        prime: [$all]


apps:
    cppcheck:
        plugs: [home]
        command: usr/bin/cppcheck
